name_stop_words = ['homepage', 'online', 'home', 'title',
					'welcome', 'https']

phone_regex = [r'[(-,. ]*[0-9]{2,4}[)-,. ]+[0-9]{5,7}',
				r'[+0-9]*[( -.,]+[0-9]{3}[-) .,]+[0-9]{3}[-) .,]+[0-9]{4}',
				r'[(-,. ]*[0-9]{4}[)-,. ]+[0-9]{3}[()-,. ]?[0-9]{2}[()-,. ]?[0-9]{2}',
				r'[(-,. ]*[0-9]{4}[)-,. ]+[0-9]{3}[()-,. ]?[0-9]{3}',
				r'[(-,. ]*[0-9]{2}[)-,. ]+[0-9]{4}[()-,. ]?[0-9]{4}']


email_keywords = ['help', 'faq', 'info', 'support', 'hello']

js_keywords = ['ngMeta']

categories = {'Auto Locksmith': r'[auto|automotive|automobile|car]{1}.locksmith',
                'Auto Repair Services': r'[auto|automotive|automobile|car]{1}.[repair|mechanic]', 
                'Auto Upholstery Repair': r'[auto|automotive|automobile|car]{1}.upholstery',
                'Bicycle Repair': r'[bicycle|bike].[repair|mechanic|technic]', 
                'Car Wash': r'[auto|automobile|car].[wash|detailing]', 
                'Driving School': r'driv.* [school|course]',
                'Hoverboard & Segway Repair': r'hoverboard-segway-repair', 
                'Lawn Equipment Repair': 'lawn-equipment-repair',
                'Motorcycle Repair': 'motorcycle-repair', 
                'Towing Services': 'towing-services',
                'Air Conditioner Installation': 'air-conditioner-installation', 'Air Duct Cleaning': 'air-duct-cleaning',
                'Bathtub Installation & Replacement': 'bathtub-installation', 'Carpenter': 'carpenter',
                'Carpet Installation': 'carpet-installation', 'Deck Building & Repair': 'deck-builder',
                'Door Services': 'door-service', 'Drain Cleaning': 'drain-cleaning', 
                'Drywall Installation': 'drywall-installation', 'Electrician': 'electrician',
                'Exterior Door Installation': 'exterior-door-installation', 'Flooring Contractors': 'flooring',
                'Furniture Assembly & Repair': 'furniture-assembly-repair', 'Garage Door Installation': 'garage-door-installation',
                'Garage Door Repair': 'garage-door-repair', 'General Contractors': 'general-contractors',
                'Handyman': 'handyman', 'Hardwood Flooring': 'hardwood-flooring', 'Heating Installation': 'heating-installation',
                'HVAC Repair': 'hvac-repair', 'HVAC Services': 'hvac', 'Laminate Flooring': 'laminate-flooring',
                'Painting Contractors': 'painting-contractors', 'Piano Tuning': 'piano-tuning', 'Plumber': 'plumber',
                'Remodeling Services': 'remodeling-services', 'Spray Foam Insulation': 'spray-foam-insulation',
                'Tile & Ceramic Flooring': 'tile-and-ceramic-flooring', 'Tile Contractors': 'tile-contractors',
                'TV Installation': 'tv-installation', 'Vinyl & Linoleum Flooring': 'vinyl-and-linoleum-flooring',
                'Water Heater Installation': 'water-heater-installation', 'Water Heater Repair': 'water-heater-repair',
                'Welding Services': 'welding-services', 'Window Installation': 'window-installation',
                'Window Repair': 'window-repair', 'Bartenders': 'bartenders','Boudoir Photographers': 'boudoir-photographers',
                'Bounce House Rentals': 'bounce-houses', 'Catering': 'catering',
                'Commercial Photographers': 'commercial-photographers', 'DJ & MC': 'dj-mc',
                'Event Photographers': 'event-photographers', 'Event Planning': 'event-planner',
                'Face Painting': 'face-painting', 'Family Photographers': 'family-photographers',
                'Flower Delivery': 'flower-delivery', 'Limo Services': 'limo-services',
                'Party Entertainment': 'party-entertainment', 'Party Equipment Rental': 'party-equipment-rental',
                'Personal Chef': 'personal-chef', 'Photographers': 'photographers',
                'Portrait Photographers': 'portrait-photographers', 'Promotional Video Services': 'promotional-video-service',
                'Table & Chair Rentals': 'table-chair-rentals', 'Videographers': 'videographers', 'Wedding DJ': 'wedding-dj',
                'Wedding Officiants': 'wedding-officiants', 'Wedding Photography': 'wedding-photography',
                'Wedding Planner': 'wedding-planners', 'Wedding Videography': 'wedding-videography', 'Balayage': 'balayage-hair', 
                'Barbers': 'barbershop', 'Box Braids': 'box-braids', 'Crochet Braids': 'corchet-braids',
                'Eyebrow Tinting': 'eyebrow-tinting', 'Eyelash Extension': 'eyelash-extension', 'Fashion Design': 'fashion-design',
                'Hair Extensions': 'hair-extensions', 'Hair Stylist': 'hair-stylist',
                'Henna Tattoos Artist': 'henna-tattoos-artist', 'Image Consultant': 'image-consultant',
                'MakeUp Artist': 'makeup-artist', 'Nail Services': 'nail-services', 'Nutritionist': 'nutritionist',
                'Permanent MakeUp': 'permanent-makeup', 'Personal Stylist': 'personal-stylist',
                'Personal Trainers': 'personal-trainers', 'Sew in': 'sew-in', 'Skin Care': 'skin-care', 'Tailors': 'tailors',
                'Tattoo Artist': 'tattoo-artist', 'Wedding Hair & Makeup Artist': 'wedding-makeup-artist',
                'Animal Control': 'animal-control', 'Ant Control': 'ant-exterminators',
                'Appliance Repair & Installation': 'appliance-repair-installation', 'Bathroom Design': 'bathroom-designers',
                'Bed Bug Control': 'bed-bug-control', 'Cell Phone Repair': 'cell-phone-repair',
                'Closet Organization': 'closet-organizers', 'Computer Repair': 'computer-repair',
                'Computer Services': 'computer-services', 'Decorating': 'home-decorators',
                'Dry-cleaning, Laundry & Alteration': 'dry-cleaning-laundry-alteration',
                'Grocery Shopping & Delivery': 'grocery-shopping-delivery', 'Interior Designer': 'interior-designer',
                'Kitchen Design & Planning': 'kitchen-designers', 'Landscape Designers': 'landscape-designers',
                'Lighting Design Services': 'lighting-designers', 'Locksmith': 'locksmith', 'Moving': 'moving',
                'Pest Control': 'pest-control-services', 'Piano Movers': 'piano-movers',
                'Pool Table Movers': 'pool-table-movers', 'Rat Control': 'rat-control',
                'Security Installation': 'security-installation', 'Self Storage': 'self-storage',
                'Termite Control': 'termite-control', 'Virus Removal': 'virus-removal',
                'Wasp & Bee Removal': 'wasp-bee-removal', 'Apartment Cleaning': 'apartment-cleaning',
                'Appliance Cleaning': 'appliance-cleaning', 'Carpet Cleaning': 'carpet-cleaning',
                'Commercial Cleaning': 'commercial-cleaning', 'House Cleaning': 'house-cleaning',
                'Housekeeping': 'housekeeping', 'Janitorial Services': 'janitorial-services', 'Maids': 'maids',
                'Mattress Cleaning': 'mattress-cleaning', 'Move Out Cleaning': 'move-out-cleaning',
                'Office Cleaning': 'office-cleaning', 'Upholstery Cleaning': 'upholstery-cleaning',
                'Window Cleaning': 'window-cleaning', 'Chimney Services': 'chimney-services',
                'Concrete Contractors': 'concrete-contractors', 'Demolition Services': 'demolition-services',
                'Fence Contractors': 'fence-contractors', 'Fence Repair': 'fence-repair', 'Firewood': 'firewood',
                'Garbage Removal': 'garbage-removal', 'Gardening': 'gardening', 'Gutter Cleaning': 'gutter-cleaning',
                'Gutter Installation & Repair': 'gutter-installation-and-repair', 'Hardscape Contractors': 'hardscapers',
                'Landscaping': 'landscaping', 'Lawn Care': 'lawn-care', 'Masonry Contractors': 'masonry-contractors',
                'Pool Buildings': 'pool-buildings', 'Pool Cleaners': 'pool-cleaners', 'Pool Maintenance': 'pool-maintenance',
                'Pressure Washing': 'pressure-washing', 'Roof Cleaning': 'roof-cleaning', 'Roofing Contractors': 'roofing',
                'Roofing Installation & Repair': 'roofing-installation-and-repair', 'Snow & Ice Removal': 'snow-ice-removal',
                'Sprinkler Repairs': 'sprinkler-repairs', 'Tree Services': 'tree-services', 'Yard Clean-Up': 'yard-clean-up',
                'Aquarium Services': 'aquarium-services', 'Dog Training': 'dog-training', 'Horse Boarding': 'horse-boarding',
                'Horse Training': 'horse-training', 'Pet Daycare & Boarding': 'pet-daycare-boarding',
                'Pet Groomers': 'pet-groomer', 'Pet Sitters & Walkers': 'pet-sitting-and-walking',
                'Veterinary Services': 'veterinary', 'Academic Writing': 'academic-writing',
                'Bankruptcy Lawyers': 'bankruptcy-lawyers', 'Business Lawyers': 'business-lawyers',
                'Civil Rights Lawyers': 'civil-rights-lawyers', 'Copywriting': 'copywriting',
                'Criminal Defense Attorneys': 'criminal-defense-attorneys', 'Divorce Lawyers': 'divorce-lawyers',
                'Essays Writing & Editing': 'essays-writing-and-editing', 'Family Lawyers': 'family-lawyers',
                'Immigration Lawyers': 'immigration-lawyers', 'Lawyers': 'lawyer', 'Notary Services': 'notary-services',
                'Personal Driver': 'personal-driver', 'Personal Injury Lawyers': 'personal-injury-lawyers',
                'Private Detective': 'private-detective', 'Resume Writing': 'resume-writing',
                'Tax Preparation': 'tax-preparation', 'Translation Services': 'translator',
                'Writing & Editing': 'writing-editing-services', 'Babysitting': 'babysitters',
                'Beauty Schools': 'beauty-schools', 'Caregiver': 'caregiver', 'Chinese Lessons': 'chinese-lessons',
                'Cooking Lessons': 'cooking-lessons', 'Dancing Lessons': 'dancing-lessons', 'Daycare': 'daycare',
                'Drawing Classes': 'drawing-lessons', 'English Lessons': 'english-lessons', 
                'French Lessons': 'french-lessons', 'Horseback Riding': 'horseback-riding',
                'Italian Lessons': 'italian-lessons', 'Japanese Lessons': 'japanese-lessons', 'Language Classes': 'classes',
                'MakeUp Lessons': 'makeup-lessons', 'Martial Arts': 'martial-arts', 'Music Lessons': 'music-lessons',
                'Other Classes': 'other-classes', 'Photography Classes': 'photography-classes',
                'Piano Lessons': 'piano-lessons', 'Portuguese Lessons': 'portuguese-lessons',
                'Private Tutoring': 'private-tutor', 'Russian Lessons': 'russian-lessons',
                'Singing Lessons': 'singing-lessons', 'Spanish Lessons': 'spanish-lessons',
                'Sport Lessons': 'sport-lessons', 'Surfing lessons': 'surfing-lessons',
                'Swim lessons': 'swim-lessons', 'Tennis lessons': 'tenis-lessons'}